---
title: "Introduction To MiamiR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction_To_MiamiR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup}
library(MiamiR)
```

Here's how to annotate the coordinates of your data with RSIDs for the index SNPs on each chromosome

```{r, results="hide", warning = FALSE, message = FALSE}
Labelled_Data <- Annotate_Data(Data = Intelligence_Sum_Stats,
                        Chromosome_Column = "CHROM",
                        Position_Column = "GENPOS", SNP_ID_Column = "ID",
                        PValue_Column = "P", Build = "HG19")



```

Let's inspect the data before plotting:

```{r}

print(head(Labelled_Data, n = 10))

```

Here's how to plot a the summary statistics of one dataset with a manhattan


```{r, results="hide", warning = FALSE, message = FALSE}
Manhattan_Plot <- Single_Plot(Data = Labelled_Data,
                        Chromosome_Column = "CHROM",
                        Position_Column = "GENPOS", SNP_ID_Column = "ID",
                        PValue_Column = "P",
                        Title = "Intelligence",
                        Chromosome_Colours = c("blue", "turquoise"),
                        File_Name = "Manhattan_Plot")


```
```{r, results="hide", warning = FALSE, message = FALSE,  fig.width=30, fig.height=15, dpi=900, out.width="100%"}
# Your ggplot code here
print(Manhattan_Plot)
```

Here's how to plot a the summary statistics of two datasets with a miami - automatically printed


```{r, results="hide", warning = FALSE, message = FALSE}



Miami_Plot <- Miami_Plot(Top_Data = Intelligence_Sum_Stats, Bottom_Data = Household_Income_Sum_Stats,
                       Top_Chromosome_Column = "CHROM",
                       Top_Position_Column = "GENPOS", Top_SNP_ID_Column = "ID",
                       Top_PValue_Column = "P",
                       Top_Colour_One = "green", Top_Colour_Two = "purple",
                       Bottom_Colour_One = "green", Bottom_Colour_Two = "purple",
                       Bottom_Chromosome_Column = "CHROM",
                       Bottom_Position_Column = "GENPOS", Bottom_SNP_ID_Column = "ID",
                       Bottom_PValue_Column = "P",
                       Top_Title = "Intelligence", Bottom_Title = "Household Income",
                       File_Name = "Miami_Plot", Width = 30, Height = 15, Quality = 900,
                       File_Type = "jpg")







```




```{r, results="hide", warning = FALSE, message = FALSE,  fig.width=30, fig.height=15, dpi=900, out.width="100%"}
# Open a new page for grid drawing
grid::grid.newpage()

# Draw the Miami_Plot grid object
grid::grid.draw(Miami_Plot)

```

